### ISSUE TITLE
Can I create a web service using this project?

### ISSUE THREAD

**Issue by codeMonkey-shin** [AxaFrance/SlimFaas#33]
What I want to do is create a service that is automatically deployed when a user logs in, turns on their own web IDE, and pushes code from that IDE. Additionally, we are considering a function that executes multiple functions at once like faas flow. Is slimfaas more efficient than openfaas?

**Comment by guillaume-chervet** [comment]
Hi @codeMonkey-shin , sorry for the delay. I did not see your issue. Tag me the next time :)

Slimfaas do not hide docker logic behind the sceene. 
If you use a continuous integration of course you can use slimfaas like you need.

**Comment by guillaume-chervet** [comment]
We historycally use Openfaas.
Slimfaas is free under MIT licences.
We use it in production in big microservice architecture.

**Comment by guillaume-chervet** [comment]
Hi @codeMonkey-shin ,

Did you make a try?

**Comment by guillaume-chervet** [comment]
hi @codeMonkey-shin , I close the PullRequest. Feel Free to reopen it if you need.
