### ISSUE TITLE
Is is possible to have k8s api permission limited to a namespace scope

### ISSUE THREAD

**Issue by haarisedhi102** [AxaFrance/SlimFaas#35]
The service account Cluster role slimfaas-full-access has broad permissions at a cluster level. Is it possible for slimfass to run properly while relying only utilizing Role at a namespace level.

**Comment by guillaume-chervet** [comment]
Hi @haarisedhi102 , I am not a kubernetes expert. The demo give full access because i struggule to set it up. I can update the demo with the minimum role required.
But in intern at AXA France we use minimum required rôles.

**Comment by guillaume-chervet** [comment]
In fact slimfaas just use list and scaleDeployment,  list and scale statefulset. For the moment, i will plug watch api soon.

**Comment by haarisedhi102** [comment]
And list an scale statefulset is recently added right? So for the most basic functionality, only list and scaleDeployment would be required? 
      serviceAccountName: slimfaas
is changing this line in the deployment yaml the only thing required to use a different/existing service account?

**Comment by haarisedhi102** [comment]
Updating the demo with minimum api requirements will be very helpful, Thank you

**Comment by guillaume-chervet** [comment]
I will try to dobit today @haarisedhi102 , after i will be in one week holiday.

**Comment by guillaume-chervet** [comment]
hi @haarisedhi102 ,

I have update the demo with : https://github.com/AxaFrance/SlimFaas/blob/main/demo/slimfaas-serviceaccount.yml
is it what you needed?
